### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by CZWsir** [3tinkers/TKImageView#1]
有没有方法让它一开始就在中间，以固定的尺寸，正方形的

**Comment by 3tinkers** [comment]
你好，上一次更新中追加了一个scaleFactor属性，用于在初始化的时候设置裁剪框的缩放比例，按照你的需求，可以在初始化的时候设置cropAspectRatio = 1，scaleFactor=0.5（或者其他你觉得合适的尺寸）
